default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  # Esto busca la clave en config/credentials.yml.enc
  password: <%= Rails.application.credentials.dig(:db_development, :local_db_password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: realtime_chat

test:
  <<: *default
  database: realtime_chat_test

production:
  primary: &primary_production
    <<: *default
    database: realtime_chat_production
    username: realtime_chat
    password: <%= ENV["REALTIME_CHAT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: realtime_chat_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: realtime_chat_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: realtime_chat_production_cable
    migrations_paths: db/cable_migrate
